### PR TITLE
Replacing componentWillReceiveProps with componentDidUpdate

### PR DESCRIPTION
**Pull request by korbav**
Replacing componentWillReceiveProps with componentDidUpdate to avoid console warnings.

### CODE REVIEW

**Comment by korbav** [comment]
Hi @serprex, sorry for the bump. Any blocker that would prevent its integration?

**Comment by serprex** [comment]
@korbav nope, sorry for missing this the first time around, thanks for pointing it out

**Comment by korbav** [comment]
@serprex Wonderful, thank you! Would you mind publishing the updated version to npm as well? Thanks!

**Comment by serprex** [comment]
I published & deprecated `0.6.2`. On my code componentDidUpdate is raising an error over an infinite setState loop

**Comment by korbav** [comment]
@serprex Thanks a lot for your reactivity. It seems you (probably mistakenly) cancel this PR during the process, what's now in the master branch (and  also published to npm) corresponds to the pre-PR codebase : 

image

image

**Comment by serprex** [comment]
I reverted it with 0.6.3 because of the aforementioned regression

**Comment by korbav** [comment]
> 
> 
> I reverted it with 0.6.3 because of the aforementioned regression

Oh I didn't notice that while testing in on my side, sorry, I'll investigate that, because definitely, we need to get rid of the deprecated UNSAFE_* methods.

By the way, would you have a reproducible case to share (codesandbox or other) ? 0.6.2 runs well for me

**Comment by serprex** [comment]
I use react-motion for https://github.com/serprex/openEtG which raised an error once a card was played. I'll try get to looking into things this weekend, until then you can use `=0.6.2` in your `package.json`

**Comment by korbav** [comment]
> 
> 
> I use react-motion for https://github.com/serprex/openEtG which raised an error once a card was played. I'll try get to looking into things this weekend, until then you can use `=0.6.2` in your `package.json`

I'm trying to run your project to figure that out but I'm failing to build it (`etg_bg.wasm` seems to be inexistent in rs/pkg).

First thought trying to infer your code, I noticed you make use of the `onRest` callback, in which you call the `setState` method, unconditionally, which will trigger indeed an endless loop since, behind the scene, Motion will itself sets his own state, causing `onRest` to re-run and then your `onRest` callback will itrelf run again and so on. According to various sources, this implementation is not a good practice : `https://gist.github.com/heygrady/9f447b215da5c4222168c773f15c9e40`

I can't be sure for now whether this is more a problem of implementation or not but it seems to me that the `componentDidUpdate` migration created in this PR is the way to go and that the original library should have been updated this way as well. 

That being said, this is clearly a breaking change and I was unaware of it. Thus, my opinion would be to go up with a `v1.0.0` to prevent any unexpected change when people update their codebase. 
We can also find a fix for your current codebase to make it compatible again.

**Comment by korbav** [comment]
Hi @serprex You might have missed my last comment, it would be wonderful to get your thoughts! 👍

**Comment by serprex** [comment]
I think it's important to understand I only host @serprex/react-motion for openEtG. Ideally upstream would update & I'd immediately get rid of this repo. So I'm not looking to progress development in backwards incompatible ways (ie where a change made in openEtG for a decision made here wouldn't be necessary if that decision isn't made for react-motion in an alternate universe where it continues development)

I'd recommend you publish your own npm package with this `componentDidUpdate` fork

My own hope would be to replace `componentWillReceiveProps` with `getDerivedStateFromProps`, but the implementation is rather impure so it'd involve quite a bit of change. Which is goes against what I wrote above

Considering I only use Motion/TransitionMotion/spring I should probably drop usage of react-motion for some simpler in-tree motion components

**Comment by korbav** [comment]
> 
> 
> I think it's important to understand I only host @serprex/react-motion for openEtG. Ideally upstream would update & I'd immediately get rid of this repo. So I'm not looking to progress development in backwards incompatible ways (ie where a change made in openEtG for a decision made here wouldn't be necessary if that decision isn't made for react-motion in an alternate universe where it continues development)
> 
> I'd recommend you publish your own npm package with this `componentDidUpdate` fork
> 
> My own hope would be to replace `componentWillReceiveProps` with `getDerivedStateFromProps`, but the implementation is rather impure so it'd involve quite a bit of change. Which is goes against what I wrote above
> 
> Considering I only use Motion/TransitionMotion/spring I should probably drop usage of react-motion for some simpler in-tree motion components

I got you, I think it's generally always a good idea to focus the efforts on the same repo but I'll follow your advice anyway, thanks for the collaboration :)

**Pull request merged**
